### ISSUE TITLE
jus lié の参照先を原書p.14 Jus de veau lié にすべて収斂させるべきか

### ISSUE THREAD

**Issue by lespoucesverts** [lespoucesverts/escoffier-translation-jp#116]
jus lié tomaté, jus lié à l'estragon のようにレシピがきちんと出ているものは別として、通常は fonds de veau brun とか fonds de volaille などをベースに、でんぷんでとろみを付けますよね。ただ、それを明確に書いてくれていないケースが多いので、上述のようにすべて jus de veau lié に収斂させちゃうか、索引に拾わないか、の2択になっちゃうと思うんですが、どうでしょうか? ご意見よろしくお願いします。

**Comment by kwikj** [comment]
結局、jus de veau lièで まとめざるを得ないと思います。索引に載っている事が この場合、より重要かと存じますが… 手間がかかるのは明白なのでこれ以上はなんとも言いがたいです…

**Comment by lespoucesverts** [comment]
ありがとうございます。やはりそうなりますよね、索引として入れるかを考えると。たとえばガルニチュールの最初のほう、Alsacienne は添えるのがPièce de Boucherie, Filet de boeuf, tournetos だから、明確に Jus de veau lié を指定していますが、そのすぐ下の、Andalouse は Pièce de Boucherie et Volaille に添えるとあって、Volaille も鶏の場合だと、比較的自然な流れて Fonds de volaille をベースにする可能性を残しているんだと思いますが、Jus lié としかない。こういうケース、意外と多いです。これはまだロジカルに考えられるんですが、Lorette の場合、添える対象がノワゼット、トゥルヌドで、ガルニチュールの方には鶏のクロケットがくる。これも Jus lié としか書いてくれていないんです。Jus lié は本文で、やがてエスパニョルにとって代わるだろう、と記しているのに、1パターンしかレシピがないというのも……現実にはフォンドヴォーをベースにしたソースということになるとは思うんですが……

こういうのはコマンドをさしあたり入れておいて、後で考えなおしてそのコマンドだけ消せば索引から抜くことも可能ですので、**とりあえず**収斂させてしまいましょうか?

**Comment by kwikj** [comment]
なにしろエスコフィエ本人が jus lié推しなのは明白で(温野菜にはバターを加えたjus,    etc…)、しかも本文では「素材のjus」を使うのがよろしい、とあるにもかかわらず(あえて？)掘り下げていないので 厳密には個々のレシピ解釈による、という事なのでしょうが… 視点を変えて

**Comment by kwikj** [comment]
視点を変えてフォンドヴォー ベースでも ほぼすべて(明記されていない限り)料理として成り立つと言えるかと思います。

**Comment by kwikj** [comment]
すみません、先程 押し間違えて閉じてました…

**Comment by lespoucesverts** [comment]
あ、操作ミスかな、とは思ったんですが（笑。いまちょうど逆引き索引用のコマンドをひたすら作成しておりまして……

確かにエスコフィエというか『料理の手引き』の本文は「ジュ」イチオシですよね。実際、ほぼその通りの歴史を辿っていって、しまいには「水の料理」にまでいったわけですから。ただ、当時としてはちょっと「もの足りない」印象があったのか、教本だからあえてリスクある部分は避けたのか……

それはともかく、フォンドヴォーで大抵のものは成立しちゃうから、収斂させるという考え方と、厳密にテクスト解釈をしてフォンドヴォライユあたりの可能性を残すべきか、注釈ならそれで曖昧さを残していいんですが、ソースからの逆引き索引として考えた場合どうか、というのが悩みの中身です。（ジビエのフュメの場合は特に書いてあることが多いから問題ないと思うんですが）

**Comment by lespoucesverts** [comment]
ついでに、まだ外に出せる状態じゃないんですけど、この「ソースからの逆引き索引」、なんか本気で凄いものになりそうな気がしています。普段なんとなく作る気もなく読んでいると流してしまいがちな、「え? こんなところでドゥミグラス使うの?」とか、スビーズ（ソースなのかアパレイユなのかいまひとつ不明確ですけど）の使われどころとか、順に読むだけじゃわからないし、ましてや必要なレシピだけしか見てなかったら全然気づかないでしょうし、逆にそういう俯瞰図が出来ると、複数のレシピの組み合わせとか再構成もかなり面白くできるのでは、と思っています。ここに気づいた神楽坂のアイデア主はさすがとしか言いようがないです。

**Comment by kwikj** [comment]
全くおっしゃる通りで、
1. 大雑把(と、いうか原書通り)に括ると 逆引きの意味が薄れる
2. いまだかつて 目にした事の無い「料理の手引き」へのアプローチの仕方ですから新しい発見がある(以外なモノ同士がリンクしているかも…三次元的視点)。
3. たとえ大雑把(?)だとしても画期的
…ちなみに、ですが バルボの店ではjus de canard しか使っていません…あ、コレ秘密でした！
現状、veauで括っておいて のちに必要あれば掘り下げる、というのが現実的かと…

**Comment by lespoucesverts** [comment]
そうですね、特に指定のない jus lié は索引上では jus de veau lié に収斂させちゃって、個々のレシピの注および、どこかで「ただし書き」を付けるといった方法のほうが現実的のように思います。では、いったん収斂させてみて、全体を眺めてから再検討ということで、よろしくお願いします。クローズします。いつもありがとうございます。

**Comment by lespoucesverts** [comment]
jus de canard ですか……鬼平犯科帳に出てきた鴨鍋を思いだしました。フツーに醤油とか使ってるみたいですから、相性はいいでしょうね。あ、ここフルオープンですので「ヒミツ」は程々にお願いします。
