### ISSUE TITLE
viande de boucherieの注について

### ISSUE THREAD

**Issue by lespoucesverts** [lespoucesverts/escoffier-translation-jp#12]
viande de boucherie という言い方がありますよね。注が長くなりそうなこともあって、ここまでまったく注釈なしに、「牛、羊肉」と訳してきました。ちなみに『料理の手引き』だとviande de boucherie に agneau は含まれません。だから「仔羊」じゃなく「羊」mouton なんです。いまの教科書だと agneau も含めるのが一般的になっていますが……
--
さて、注をつけるとして、どんな感じに書くといいでしょう? 僕が書くと、歴史的経緯からになって、職業別の許認可や同業者組合の利権争いやら、とんでもなくたいへんなことになりそうなので、簡潔でわかりやすい注を募集します。

料理人さんの知識としては基本中の基本の筈なんですけど、突っこんで説明するとキリがないというまことに困った用語です。

つまりですね、何もご存知ないであろう調理師学校の学生さんに、僕が素でやってしまうような説明をしたって、頭に何も残らないだろうというのを危惧しているんです。ちょっと気の利いた子なら「どうして豚や鶏は入らないの?」って疑問に思うでしょうし、そうなると厄介な説明が延々と続くことになりかねない。ここはひとつ有無をいわさずガツンと納得させるような言葉はないものか、とお知恵をお借りしたいわけです。

ちなみに、旧訳はどうなってるか見たらpour viande de boucherie は基本的に「肉料理用」みたいですね。いいかげんだなぁ。肉料理は肉料理だけど、何の肉なのかある程度は限定してあげないといけませんよね。

あと『フランス　食の事典』だと「畜殺肉」というおっかない訳語が説明なしで出てまして、これは最新の『プロのためのフランス料理仏和・和仏辞典』（柴田書店）でも同じでした。これはちょっとよろしくないか、と。

**Comment by lespoucesverts** [comment]
論点というか問題点の追加です。pièce de boucherie という表現がよく出てきます。通常、pièce de boeuf だといわゆる「ランイチ」のあたりの塊肉をブレゼなどにしますが、pièce de boucherie だと羊も入りますでしょうか? 入る場合は、サドルから? このあたり具体的にご教示いただけませんでしょうか?

**Comment by kwikj** [comment]
viande de bocherie… 簡単そうでとても難しいです。ですので、簡潔に「 白身以外の畜産精肉(馬肉含む)。ではいかがでしょうか…

**Comment by lespoucesverts** [comment]
レスありがとうございます。そうなんですよね、馬肉も含んじゃって、何でしたっけ、boucherie de hippophagique でしたか、専門店があるんですよね。boucherie 自体は「肉屋」ですから、「肉屋（=boucherie）が伝統的に主に扱ってきた、白身肉を除く畜産精肉のこと。具体的には牛、羊の赤身肉のことだが馬肉も含む」ってな感じだとどうでしょうか? これで大多数が納得してくれるなら、採用させていただきたいです。

**Comment by kwikj** [comment]
少しは お役に立てたようで嬉しいです。あと、pièce de boucherieには羊も含まれると認識しております。具体的にはselleからquasiにかけての「筋肉質で整った」部位がそれにあてはまるかと存じます…

**Comment by lespoucesverts** [comment]
いつもありがとうございます! 簡潔に、というところで今回はえらく難儀してしまいまして…… pièce de mouton って言いますが、どうも現物を知らないせいかピンと来ませんで、助かります。selleからquasi ってことは、日本語だと「鞍下肉から腿上部にかけての部位」という感じでしょうか? 特定の名称はないですよね? 下半身肉?

**Comment by kwikj** [comment]
いわゆる下半身肉ですが、より具体的に記すならば、鞍下肉から上部モモ肉(シキンボ)まで、 という事になろうかと存じます…

**Comment by lespoucesverts** [comment]
ありがとうございます!!! たぶんこれの説明が必要になるのはルルヴェとアントレに入ってからだとは思うんですが「鞍下肉から上部モモ肉（シキンボ）まで」、使わせていただきます。

で、おそらくルルヴェとアントレの章でガツンと、viande de boucherie についても、中世のプライユールやシャルキュティエとブシェの利権などについてから例によって長々と注釈つけることになると思いますが、「とりあえず」の説明をしたかったので、今回はとても助かりました。

それにしても、気になって旧訳を見てみたら、まるっきりの誤訳とは言えないものもあるけれど、ひどいですね。「ジビエおよびシュヴルイユ仕立ての（あるいは「マリネした」牛、羊肉用」とすべきところを「漬けた鶏、肉料理用」って、なんじゃこりゃ?  ですよね。

**Comment by kwikj** [comment]
-boucherie についてはラルースでも歴史的説明が少しなされている事を鑑みれば、軽んじられないかと。。
えー、旧訳は読んでいませんが、きっと理解できる方はいらっしゃらないと思います。泣

**Comment by lespoucesverts** [comment]
たしかに、手元の2007年版もさらっとだけど歴史的な説明はありますね。プライユール（プライエ）との関係に触れてないのが残念なところですが（仔羊、うさぎ、時代によっては仔牛もプライユールに扱い権限があったんで）、豚の扱いを放棄とあるのは、シャルキュティエがブシェから独立して組合を作ったときの問題のことですね。このあたり、ルルヴェとアントレの章になったら注でおもいっきり書きますので、またよろしくお願いします。

**Comment by kwikj** [comment]
こちらこそ、またよろしくお願い致します！

**Comment by lespoucesverts** [comment]
とりあえずクローズしますね
