### ISSUE TITLE
II. ガルニチュール におけるクールブイヨンの簡潔な訳注

### ISSUE THREAD

**Issue by lespoucesverts** [lespoucesverts/escoffier-translation-jp#14]
シャンボールなんかで出てくるんですが、クールブイヨンもまた「概念」であって、具体的に「コレ」を示しずらいもののひとつだと思います。もちろん内部リンクでクールブイヨンのところに飛べるようにリンクの用意はしていますが……簡潔に、ガツンと納得させられる訳注があるといいかな、と思うのですがいかがでしょう?

**Comment by mabumen** [comment]
火を通す材料に対してひたひたに浸かる程度の量で使うことを想定したブイヨン。主に魚介類に火を通すために使われ、水、白ワイン、香味野菜、香辛料などから作ったものを使うことが多い。
なんかツッコミどころ満載な気もしますが…

**Comment by lespoucesverts** [comment]
court-bouillon はcour（クール=少ない）とbouillon（ブイヨン）の合成語。もっぱら「最小限」の量で沸騰させずに魚介類などに火を通すために用いられ、魚介用の場合は水に白ワイン、香味野菜、香辛料などを加えて事前に用意しておくのが一般的だが、香味付けの役割も大きい。またその煮汁は煮詰めてソースに加えたり、ソースのベースにするなどのかたちで利用されることが多い。……やっぱり僕が書くと長いですよね（笑。押さえておきたいポイントはもともとはcourt=少量、ということと香味付けの役割が大きいこと、ですか。現場サイドだと感覚的にそのへんはどうなんでしょうか? いまは切り身を扱うことがほとんどで、煮汁が「少量」であることの意味がほとんど失なわれちゃってるように思うんですが。

**Comment by mabumen** [comment]
煮汁を少量にする意味って、それを煮詰めてそのままソースにすることを前提としてるからでしょうか？

**Comment by lespoucesverts** [comment]
結果としてひとつの理由ではあると思います。court-bouillonné という料理名はたしか17世紀にはもう出てきたと思うんですが、ソースを別に用意するというのではなかったと記憶しています。そのままソースにしちゃった、と。あとは加熱の問題ですよね。魚1尾まるごと、ちょうどいい大きさの鍋に入れて、せいぜいひたひたくらいまでの煮汁にしたときの火の通りかたと、大きな鍋にたっぷりの煮汁を入れて火を通したときとでは仕上りはかなり違うはずです。もはやポワソニエールもテュルボティエールも各サイズとり揃えてる現場なんてないでしょうから、気軽に試してみるわけにはいかないでしょうけど……切り身だと、しょうがないからせっせとアロゼしながら火を通していく感じになっちゃうでしょうか?

**Comment by lespoucesverts** [comment]
このあたりはkwikjさんが経験とか知識が豊富だと思うので、お待ちしてます。

**Comment by kwikj** [comment]
液体が多すぎると「うまみ」が薄まる、という考えから来ていると理解しています。もちろん、ブランダードモリュなんかだと塩抜きも兼ねていますので、「ちょうど良い」液体量の意味合いは変わってきますが… 面白いのは、クールブイヨンの考え方は少し「コンフィ」に似た点がありまして、例えば鴨足肉のコンフィですと、鍋にみっちりと鴨足を立てて詰め込み、自身から出る油脂のみでコンフィにしてゆきます(ジョー・ロスタン流) 。つまり、いたずらに液体を増やさないのです。結果、エコノミゼですし、素材の持ち味も活かせます。当然クールブイヨン自体も風味豊かになる、という事かなと思います。

**Comment by lespoucesverts** [comment]
で、問題なんですが、クールブイヨンを最初に説明するときに、もともとの意味にある「少量」という概念を強調すべきかどうかなんです。というのも、ガルニチュール・シャンボールのエクルヴィスをクールブイヨンで火を通すところで注をどうするか、が悩みのタネでして。トルゥセしてもしてなくてもいい、というまことに装飾要素が高い部分でわざわざクールブイヨンを使うのは香味付けというか匂いのマスキング効果のほうが大きいような気がするんですが、トルゥセしたときのエクルヴィスの加熱ってどんな感じなのでしょうか? ご教示よろしくお願いします。

**Comment by kwikj** [comment]
自分の経験上、トルゥセはエクルヴィス を火入れした後でしか形にしませんでしたので、正直トルゥセしてからの火入れはなんとも答えられません…ただ、かなり気を使わないと腕は取れちゃいますよね…ただでさえ、暴れ回りますから…

**Comment by kwikj** [comment]
しかし、クールブイヨンの議題は怖いです… これ、能の「奥の段」、マスタークラスの着眼点かと… いやぁ 怖い 怖いです…

**Comment by lespoucesverts** [comment]
とりあえず、原稿のまま貼ります。後でコンパイルしますので、どちらかでチェックいただければ幸いです。よろしくお願いします。

#### ガルニチュール・シャンボール[^63] {#garniture-chambord}

\frsub{Garniture Chambord}

\index{garniture@garniture!chambord@--- Chambord}
\index{chambord@Chambord!garniture@garuniture ---}
\index{かるにちゆーる@ガルニチュール!しやんほーる@---・シャンボール}
\index{しやんほーる@シャンボール!かるにちゆーる@ガルニチュール・---}

（魚のブレゼの大掛かりな仕立てに添える[^62]）

* トリュフを加えてスプーンで整形した魚のファルスで作ったクネル10個。

* 長卵形の大きな、表面に装飾を施したクネル4個。

* 渦巻模様を付けた[^70]小さなマッシュルーム200 g。

* 鯉の白子を1 cm程度の厚さにスライスして塩こしょうし、小麦粉をまぶしてソテーしたもの10枚。

* オリーブ形に整形した[^64]トリュフ200 g。

* エクルヴィス[^65]6尾は[クールブイヨン](#courtbouillon-a)[^65bis2]で火を通すし、
  はさみを背に回すように整形する[^65bis]（しなくてもよい）。

* 食パンを鶏のとさかの形に切りバターで揚げたクルトン6枚。

* 魚をブレゼした際の煮汁をベースにしたソース。

[^62]: ルルヴェのこと。[第二版序文訳注](#releve)参照。19世紀前半くらい
    まではカトリックの習慣としての「小斉」が比較的厳格に守られており、
    料理人たちは四旬節やその他の小斉の日の献立としていかに豪華で美味な
    魚料理を提供するかに腐心していたのが、17〜18世紀の料理書を読むとよ
    くわかる。カレームの著書にも魚の大掛かりな仕立てのレシピが数多く収
    められている。

[^63]: シャンボールとは16世紀、ロワール河の近くに建てられた瀟洒な城の
    ある地名。このガルニチュールを添えた場合、料理名にシャンボールが冠
    される。鯉、サーモンが代表的だが、とりわけ19世紀は鯉が好まれ、カレー
    ム『19世紀フランス料理』第2巻では鯉のシャンボールだけで近代風、ロ
    ヤイヤル、レジャンスの3種の仕立てについて詳述されている
    (pp.181-189)。なお、このガルニチュールの構成も時代や料理人によって
    多少の変化があり、『ラルース・ガストロノミック』初版では、魚でつくっ
    た大小のクネル、マッシュルーム、舌びらめのフィレ、バターでソテーし
    た白子、オリーヴ形に整形したトリュフ、クールブイヨンで火を通したエ
    クルヴィス、揚げたクルトン、となっている(p.516)。

[^64]: tourner （トゥルネ）。原義は「回す」。野菜などを包丁ではなく材料
    を回すようにして皮を剥いたり整形するところからこの用語が使われるよ
    うになった。

[^65]: ecrevisse ヨーロッパザリガニ。

[^65bis2]: court-bouillon （クールブイヨン）。court は少量の意。つまり、
    原則としては少量の液体を煮汁として魚介類その他を加熱調理するのに用
    いる。また、魚介類の場合は沸騰しない程度の温度で火を通す（pocher
    ポシェ）が原則。たんなる水、塩水だけでなく、ワインや香味野菜、香辛
    料などを加えて風味付け（および場合によっては臭みのマスキング効果）
    も兼ねることがある。ただしこれはあくまでも原則論にすぎない。詳細は
    [魚料理](#poissons)の[クールブイヨ
    ン](#serie-de-courts-bouillons-de-poisson)参照のこと。なお、エクル
    ヴィスの場合は上記の「少量」にはあまりこだわらずに、後ではさみを背
    に回してやりやすくなるように鍋に入れて加熱すればいいだろう。

[^65bis]: trousser （トゥルセ）。

[^70]: 原文 canneler （カヌレ）。この場合はtourner （トゥルネ）とほぼ同義だが、凹凸の刻み模様を付けた、の意。

**Comment by lespoucesverts** [comment]
PDFもプッシュしました。pp.94-95のあたりが問題のところです。よろしくお願いします。
