### ISSUE TITLE
想定読者層の問題

### ISSUE THREAD

**Issue by lespoucesverts** [lespoucesverts/escoffier-translation-jp#16]
相変らず、想定読者層の問題で頭をかかえています。ある程度の予想はしていたことですが、「プロ」の料理人さんたちの「知識」が、僕の想定しているのとかなりズレているのでは? と感じています。FBでディスカッションにならないのも、料理写真を投稿してくれないのも、「知らないことばかりで自信が持てない」のが理由じゃないか、と。「自分の厨房じゃ王様なんでしょ?」なんて冗談が通じる雰囲気でもなく…… 原書が「ひと通りのことを知っている、経験している」レベルの料理人を対象としたものだけに、これはもとのレベルが高すぎるんじゃないか、しかもそこに100年以上の埋められない時間差がある。場合によっては「注釈」を最初から見直して、徹底的にいまの「現場」とのすり合わせをしないと難しいだけのものになってしまうのでは、と危惧しています。「学者の翻訳」を宣言しているとはいえ、持ってるだけで安心、とか、それこそ「書棚の飾り」にして欲しくはないです。

**Comment by kwikj** [comment]
なんと嘆かわしい事でしょうか… 何が残念かと申しますと、「眺めているだけ」の方々が著者御本人に編集内容の変更まで勘案していただいている状況にです… 個人的には、どうか五島さんの培ってこられた文献学的手法を遺憾なく発揮された作品を切望致しますが… きっと皆さん余計な見栄が邪魔してコメントしてくれないのかなぁなんて考えたりもしますが。

**Comment by lespoucesverts** [comment]
コメントありがとうございます。たしかに「見栄」みたいなものはあるかも知れませんね。ただ、一応は興味を持ってくださっている方が500人を越えるとなると、読者層とのマッチングは大事か、と。僕が本気で注釈をつけて、平易あるいは基礎的な部分を削ってしまうと、それこそ「学者崩れの自己満足」「象牙の塔の内側の彫物」になりかねないです。これはちょっともったいないとさすがに僕自信も思っています。どの投稿だったか、「レデュレ」という語をコメでお使いになった方がいて、僕はさいしょ何のことだかさっぱりわからず、「ひょっとして、煮詰める、のレデュイール?」と聞きかえしたことがありました。「ブランシェ」を笑えないレベルですが、今回そのあたりはスルーすることにしているので、追求しませんでした。このあたりの「ズレ」をどうやったら僕がある程度正確にきちんと認識できるかが、読み手にとって「理解できるもの」になるかどうかの分岐になるように感じています。

**Comment by lespoucesverts** [comment]
またといいますか、僕がひどく混乱する事案（?）がFBで起きまして、助け船を出してくれた方いわく、「彼は真正無垢の◯カでしょう」との由。あ、それもう僕の天敵に近い存在、読者対象としては無理もいいところ、と思ってしまいました。教師としての無力さをかつて嫌というほど某女子大で味わわされたというのに……なんか「シェフ」の立場にあればそれなりに社会的あるいは言語的なレベルにあると思い込んでいた自分もまた無垢というかナイーヴですね。ま、あの壁というか深淵はどうしようもないので、助け船を出してくださった方が「なんとかしてやる」とおっしゃってくださったのであてにしています。病気のせいですかね、過剰反応しそうになっちゃうのは……すみません、公の場で愚痴ってしまいました

**Comment by lespoucesverts** [comment]
とりあえずこの問題はクローズします
