### ISSUE TITLE
Garniture Dubarry のカリフラワー

### ISSUE THREAD

**Issue by lespoucesverts** [lespoucesverts/escoffier-translation-jp#18]
原書p.93です。初版から一貫して petit bouquet de chou-fleur, moulé en boules となっていますが、文字通りの球形にするには半円の型（ボウル）を2つ使うことになりますし、なにより「つなぎ」になるものがないと崩れて形にならないと思います。ここで示されているソース・モルネーだと半球形は可能でも、球形にしてしまうとグラティネしたときに熱でソースが柔らかくなってしまい「つなぎ」きれないのではないかと。

野菜料理の Chou-fleur au gratin (p.745)ではボウルに詰めて内側にソース・モルネーを少々流し込む、とあり、それで解釈していいのでは、と考えますがいかがでしょうか?

**Comment by kwikj** [comment]
moulés en boules, masqués〜、いやー、コレ、球形の型に入れて〜では少々無理があるので、球形(半球形)に形づくり、との意訳は不可能でしょうか… そのあとモルネーで覆ってチーズふりかけて…一応、moulerだと「かたどる」の意もありますよね…

**Comment by lespoucesverts** [comment]
ちょっと直してみました。いかがでしょうか?

* カリフラワーの花房を小さく分け、球形になるようまとめて[ソース・モル
  ネー](#sauce-mornay)で覆ったもの10個。おろした[101]チーズを振りかけ
  て高温のオーブンでこんがり焼く[100]。

[100]: gratiner （グラティネ）。また、原文を文字通りに読むと「完全な
    球形」にするようにも解釈出来るが、そのためには「つなぎ」が必要にな
    る。ソース・モルネー以外に「つなぎ」の役割を果たすものの指定がない
    ため、ここは[カリフラワーのグラタン](#chou-fleur-au-gratin)にある
    ように moulé dans un bol 「ボウルに詰める」と同様と解釈してもいい
    だろう。

[101]: râper （ラペ）

**Comment by kwikj** [comment]
解り易いと思います。グラタンの項とは著者が同一ではない…なんてオチかな、と一瞬思ってしまいました…

**Comment by lespoucesverts** [comment]
あ、著者が違うというのはあり得ますね。だから表現が違ってくる、と。

**Comment by lespoucesverts** [comment]
バージョン2です。確かにこの部分と野菜料理のところは文体がかなり違うんで、別の著者だと思います。

* カリフラワーの花房を小さく分け、小さなボウルに詰め半球形になるようま
  とめて裏返し、[ソース・モルネー](#sauce-mornay)で覆ったもの10個。お
  ろした[101]チーズを振りかけて高温のオーブンでこんがり焼く[100]。

[100]: gratiner （グラティネ）。また、原文moulés en boulesを文字通り
    に読むと「完全な球形」にするようにも解釈出来なくはないが、そのため
    には「つなぎ」が必要になる。ソース・モルネー以外に「つなぎ」の役割
    を果たすものの指定がないため、球形を維持する「つなぎ」としては熱に
    弱過ぎるだろう。ここは[カリフラワーのグラタ
    ン](#chou-fleur-au-gratin)にあるように moulé dans un bol 「ボウル
    に詰める」と同様と解釈してもいいだろう。

[101]: râper （ラペ）

**Comment by kwikj** [comment]
よりイメージしやすくなったと思います。完成形が想像出来る、これは重要な要素ですよね…

**Comment by lespoucesverts** [comment]
ありがとうございます。ではとりあえず、これでいきたいと思います。

**Comment by lespoucesverts** [comment]
まったく、デュバリー夫人は元娼婦のくせに、こんなところで悩ませられるとは……存外、クルティザーヌの名前って料理名に多いから、なんか微妙な気分になっちゃうんですよ。注に、断頭台へ連れていかれるときに唯一、狂乱し泣き叫んで命乞いした、という逸話も盛り込んじゃいましょうかね。それはロベスピエールの恐怖政治への警鐘になり得たというひとも多いんですが。

**Comment by lespoucesverts** [comment]
注に入れちゃいました。

Madame du Barry （マダムデュバリー）デュバリー夫人 （1743〜1793）
    のこと。ルイ15世の公妾であり、フランス革命により断頭台に送られ命を
    落したことで知られる。もとはシャンパーニュ地方の貧しい家庭の生まれ。
    パリに出てのちデュ・バリー子爵に囲われ、いわゆるdemi-mondaine（ドゥ
    ミモンデーヌ）、courtisane （クルティザーヌ）すなわち高等娼婦とし
    て知られるようになる。その後、ポンパドゥール夫人を亡くしたルイ15世
    が彼女を妾にすることにし、形式上、デュ・バリー子爵の弟と結婚したこ
    とにして、正式な社交界デビューを果たした。フランス革命のさなか、捕
    えられて断頭台へ連れていかれるときに、ほとんどの貴族の女性が取り乱
    さず凛として死に臨んだのに対し、デュバリー夫人ただひとりだけが狂乱
    し泣き叫んで命乞いした、という逸話が残っている。ただ、それはロベス
    ピエールによる恐怖政治への警鐘になり得たという見解も少なくない。
