### ISSUE TITLE
ベアティーユとフィナンシエール

### ISSUE THREAD

**Issue by lespoucesverts** [lespoucesverts/escoffier-translation-jp#36]
ここだと「流れ」てしまわないので。まず問題提起というか材料は[FBへの投稿（リンク）](https://www.facebook.com/groups/1548833425201180/permalink/1674528555964999/)をご覧ください。

**Comment by lespoucesverts** [comment]
FBのコメ欄にも書きましたが、Pierre de Lune, *Le Nouveau Cuisinier*, 1660, p.50. のベアティーユのラグーの現代綴りにしたものです

>Faites cuire les béatilles avec bouillon, les passez à la poêle avec lard fondu, et un peu de farine, un champignon, un paquet, sel, un peu de poivre blanc, mettez jus de citron et de mouton en servant.

**Comment by kwikj** [comment]
コメント遅れました…なんだか今週はデスマーチで… えー、ベアティーユはアレですね、フランチェスコ会の在俗会がらみでしょうから、「手仕事」細工箱とか鞠、仔羊メダルなど…いわゆる精緻な … で、もともとはやはり「包みもの」であったと考えていますが…まぁ、トリュフとソースマデラは置いといて、の話ですが…

**Comment by lespoucesverts** [comment]
そうですね。おっしゃるとおり、基本的には「包みもの」で、その中身が細かい、というところから来ているんだと思います。実際、パテの方が圧倒的に多いですし、この「ラグー」だって「煮込み」じゃないですから。なんか、ガルニチュールの段階でここまでやるのも読者にはキツいかな、という気もするんで、ちょっと先になりますがヴォロヴァンのあたりまで保留しようかなと思うんですがどうでしょうか?

**Comment by kwikj** [comment]
なるほど、ヴォロヴァンの項目にてまとめた方がきっと伝わり易いですよね。賛成です！

**Comment by lespoucesverts** [comment]
ではヴォロヴァンまで「おあずけ」ということで、いったんクローズします。
