### ISSUE TITLE
pain de la Mecque の表記

### ISSUE THREAD

**Issue by lespoucesverts** [lespoucesverts/escoffier-translation-jp#42]
[FBのグループへの投稿](https://www.facebook.com/groups/1548833425201180/permalink/1679265845491270/)で、日本語の呼び方があるか尋ねたところ、どうもなさそうなので、こちらでカタカナ書きか訳語を考える必要がありそうです。ただ単に「パン・ド・ラ・メック」とすると・が多すぎで煩いし、à la を入れるとき「アラ」とまとめてしまっているのにあわせて「パン・ドラ・メック」あるいは「アラモード」「アラフランセーズ」式に「パン・ドラメック」にすると「どら焼き」みたいな……どうしましょう? FBでは流れちゃうので、こっちに移動させて課題としたいと思います。

**Comment by kwikj** [comment]
うーん、わかりやすく「メッカ風パン」とかでしたら意も伝わりやすくなるかも知れませんが… 難しいです…

**Comment by lespoucesverts** [comment]
なにしろ「メッカ」ですから。「メッカにそんなものはない!」と言われてしまえばそれまでですし、僕はあのあたりの食というとバクラヴァとケバブくらいしか知らないんで……いずれにしても現代では作られなくなってる様子ですね。『ラルース・ガストロノミック』2007年版には見あたりません。いずれにしてもp.765の「じゃがいものマルキーズ」が形状の指定でやっぱりPain de la Mecqueかmeringue canneléeにしろということなので、そこの注をきっちり書くまでの課題にしたいかな、と思っています。うかつには書けないです。すこし時間をかけて調査してみようと思います。それにしても、ガルニチュール・マルキーズの後半部分は「じゃがいものマルキーズ」そのものの説明になっているわけですから、無駄を省いているようで、重複しているところがなんとも微妙です。

**Comment by lespoucesverts** [comment]
こちらに移動してきて正解でした。「メッカ風パン」のひとことで、思い切り誤訳してたことに気づきました。以下、生原稿なので注など化けると思いますが、のちほどPDFでご確認ください。ついでに pain de la Mecque もなんとなく「逃げ」の説明を書いてしまいました（汗。

#### ガルニチュール・マルキーズ[^180] {#garniture-marquise}

\frsub{Garniture Marquise}

\index{garniture@garniture!marquise@--- Marquise}
\index{marquise@marquise!garniture@garuniture ---}
\index{かるにちゆーる@ガルニチュール!まるきーす@---・マルキーズ}
\index{まるきーす@マルキーズ!かるにちゆーる@ガルニチュール・---}

（ノワゼット、トゥルヌド、鶏料理に添える）

1. 縁に波形の飾り模様の付いた小さなタルトレット10個を空焼きする。これに
  以下を詰める。アムレット[^181]250 gをやや低温で火を通して小さな筒切
  りにする。アスパラガスの穂先125 g、太さ1〜2 mmの千切り[^183]にしたトリュフ
  50 g、これらを、[エクルヴィスバター](#beurre-d-ecrevisse)を仕上げに
  加えた[ソース・アルマンド](#sauce-allemande)1 $\frac{1}{2}$ dLであえ
  る。

2. 濃いトマトピュレを混ぜ込んだ[じゃがいものデュシェ
   ス](#pommes-de-terre-duchesse)を絞り袋で天板に小さな卵形に絞り出し、縦中
   央にナイフなどで切れ込みを入れ、溶き卵を塗ってオーブンに入れて提供数分
   前にこんがりと焼きあげたもの[^182]20個。

[^180]: marquis / marquise 侯爵、侯爵夫人の意。

[^181]: 牛、仔牛、仔羊の脊髄（=moelle モワル）。

[^182]: ここで説明されているのは、[じゃがいものマルキー
    ズ](#pommes-de-terre-marquise)のレシピそのものといっていい内容で、
    かなりの部分が野菜料理の節にあるレシピと重複している。 形状については、巨大なコー
    ヒー豆のようなイメージでおおむねいいだろう。ここではかなり意訳した
    が、直訳すると「Pain de la Mecque （パンドラメック=メッカのパンの
    意）の形状にする」。これはシュー生地を卵形に天板に絞り出して溶き卵
    を塗り、グラニュー糖を振ってから縦中央にナイフで切れ込みを入れて焼
    くという、19世紀には比較的ポピュラーだった焼き菓子。グフェ『パティ
    スリの本』（1873年）にもレシピが2種掲載されている(pp.287〜288)。
    シュー生地とほぼ同じものを使うため、内部に空洞が出来るが、そこにク
    レーム・シャンティイなどを絞り袋を使って詰めるバリエーションもあっ
    た。この焼き菓子になぜ「メッカ」の地名が付けられているのか、また、
    トマトピュレを加えたじゃがいものデュシェスをその形状に似せて焼いた
    ものをなぜ、じゃがいものマルキーズ（=侯爵夫人）と呼ぶのかといった
    理由、由来は不明。ちなみに貴族の格としては公爵夫人（デュシェス）の
    ほうが侯爵夫人よりも一般的に上位とされた。

[^183]: julienne （ジュリエーヌ）。

**Comment by lespoucesverts** [comment]
というわけでいったんクローズします
