### ISSUE TITLE
翻訳のコツとかいろいろ

### ISSUE THREAD

**Issue by lespoucesverts** [lespoucesverts/escoffier-translation-jp#48]
スレ立てました。

この章はとりわけ初版からの変更（改悪?）が多いです。初版は同時通訳的にあたまからすらすら日本語になるのに、現行版は「うーん」と考えて「言いたいこと」を整理しないとどうにも日本語になりません。というか、「同じ話しくどくど回すなよ、爺さん」的な悪文になっているので、「聞き書き」確定、ライターさんは優秀ではない、という感じでしょうか。

**Comment by lespoucesverts** [comment]
なんとなくですが、この悪文の犯人はエミール・フェチュじゃないかと予想しています。実際のところ、ジルベールは『ラルース・ガストロノミック』初版に序文を寄せていますが、それを読むかぎり、名文とはほど遠いけれど、これほどの悪文じゃない。フェチュという人は料理史に名が残っていないんで、むしろライターかジャーナリスト的な仕事が多かったのかな、と想像しています。このテの悪文でヴァレリーとかマラルメの文章の「見た目」だけを真似た感じなんで、当時としては格好よかったのかも知れません。

**Comment by kwikj** [comment]
当時流行っていた文体まで考察されるとは… 脱帽です。正直、他の料理人方々も翻訳(もどき)に挑戦されたら良いのに、と思いますが…

**Comment by lespoucesverts** [comment]
料理書の、とりわけレシピについては料理人さんが訳をなさるほうが、間違いはかえって少なくなると思います。いまやっているガルニチュールのような箇条書きタイプの場合、名詞（完成形）が最初にきて、その後に過去分詞が列挙されるから、前から順にやっていくと考えるしかなくてそう訳しますが、先日のエクルヴィスのトゥルセのように、実際には逆にやったほうがいい、というケースも多々あるかと。

**Comment by kwikj** [comment]
納得です。つぎはレシピ及びファイル名入力に関して尽力させていただきたく存じます。ちなみに、なのですが 翻訳のコツ( 特にセンテンス長めの分かりづらい文章 )はあるのでしょうか？

**Comment by kwikj** [comment]
御返答ありがとうこざいます。自分のフランス語は独学ですので正直、カベに当たる事も多いです… ですが今回は良い機会を得ましたので めげずに挑戦させていただこうと思っております！

**Comment by lespoucesverts** [comment]
素晴らしい!! 是非!!!

**Comment by lespoucesverts** [comment]
そうそう、原稿をプルしてくださる際、日本語で40文字くらいで改行を入れてくださると後のdiffが見やすくなるのと、僕のほうでTeXファイルに変換するときにエラーが出にくくなるので、出来るだけ小まめに改行していただけると助かります。markdownは空行が段落の印になりますが、いくつ空行を入れても1つ扱いという仕様なので、空行が多めな分には問題ありません。

エディタをお使いになる場合はGithub謹製のAtomがおすすめです。https://atom.io/ でDLできます。Mac, Win, Linux対応です。僕の使っているEmacsだとTeXへの変換とPDFの作成がほぼショートカットキーだけで出来るんですが、なにしろクセの強いエディタなので……

**Comment by lespoucesverts** [comment]
スレタイ変えました

**Comment by kwikj** [comment]
なるほど。改行の件、やはりそうだったんですね。気になっておりました。
今後ともよろしくお願い致します。

**Comment by lespoucesverts** [comment]
こちらこそどうぞよろしくお願いします!!!

ちなみに僕の使っているEmacsというエディタだと、横幅の文字数を設定ファイルに書いておくと、ESC+Qで一瞬で1行40字でリンクとかが切れないように揃えてくれちゃうんです。ATOMにも似たようなパッケージがあったと思います。ちょっと確認してみますね。

**Comment by lespoucesverts** [comment]
すみません、自分のAtomの設定をみたんですが、よくわかりませんでした。そういうパッケージがあったような気はするんですが……

**Comment by kwikj** [comment]
お気遣いありがとうこざいます…こちらで色々試してみます。幸いなことに家内がその方面には結構強いので…

**Comment by lespoucesverts** [comment]
Atom用、改行の整形ツール、ようやく見つけました。[reflow-japanese](https://atom.io/packages/reflow-japanese)というパッケージです。Preference>install でreflow-japaneseと入力すれば検索して、インストール可能になります。説明文にしたがって、keymapsにちょっと書き込む必要があるかも知れません。デフォルトの長さを80にすると、日本語40文字で強制改行してくれます。

**Comment by lespoucesverts** [comment]
別途インストールすると便利なプログラム
* [pandoc](http://pandoc.org/)……文書変換プログラムです。Mac, Win, Linux対応ですが、英語サイトです。
* TeX……Macの場合は上記PandocのサイトにあるTeXLiveのBasicインストールに日本語関係などを追加するとディスクの節約になります。Windowsで推奨されているMikTeXについてはまったく知識がないのですみません。TeX入門としては、[TeXWiki](https://texwiki.texjp.org/?はじめての方へ)あたりからお読みになるといいでしょう。

なお、このプロジェクトでは、pandoc拡張Markdown書式で書いた原稿を、pandoc でLuaLaTeX 用のTeXファイルに変換して、LuaLaTeXでPDFにしています。分数の書き方は

    $\frac{分子}{分母}$

ですが、よく使うものを日本語入力で辞書登録して「にぶんのいち」で

    $\frac{1}{2}$

のように覚えさせておくとラクになります。通常の原稿作成では、

    \index{よみかた@見出し語}
    \index{アクサンなしのフランス語@アクサン付きフランス語}

の原則を覚えていただければ大丈夫かと思います。

**Comment by kwikj** [comment]
ご丁寧にありがとうございます。タイピングも人並みに出来るように…頑張ってみます！

**Comment by lespoucesverts** [comment]
あわてず、無理なさらない範囲でおねがいします! そういえば、タイピングは練習サイトとかありましたね……自分でやってるわけじゃないので責任は持てませんが、[このあたり](http://www.pken.com/tool/typing.html)がお手軽かと思います。が、

基本的に、早く打てるようになるコツは

* ホームポジション（左手人差し指がF、右手人差し指がJ)を崩さないようにすること
* 最初は fjfjfjfj とかghghghgh とか zpzpzpzpなどとやって、指自身がキーの位置を覚えるような感じの練習がいいです
* その次は、簡単な英単語を繰り返し打つ練習
* フランス語入力は無理にフランス語配列（AZERTY）にせず、カナダ式あたりのアクサン記号と文字を組みあわせるタイプのQWERTYベースのものを使ったほうがラクだと思います（僕はAZERTYで覚えちゃいましたが、英語やイタリア語を打つときにかえって面倒だったりしますので、おすすめしません）
* 手元を見ないで、常に画面を見て打つように心がけるのが早くなるコツとしていちばん大切だと思います

**Comment by lespoucesverts** [comment]
ひととおりドキュメントを書いたのでクローズします
