### ISSUE TITLE
料理人さんたちがよく大綬か中綬みたいなの首からぶら下げて写真に写ってるけどあれって何なの?

### ISSUE THREAD

**Issue by lespoucesverts** [lespoucesverts/escoffier-translation-jp#69]
FBじゃちょっと書けそうにないのでこちらで。

まず、**小綬、略綬はないのか**? という疑問。ま、**レジオンドヌール**も農事功労賞もいまどきは大安売りだからいいんだけど、大綬なら太いリボンで袈裟がけ、中綬ならやや細いリボンで首からふつうにかけますよね、フランスの勲章の場合。で、料理人さんたちのはその間? 太いリボンを首にふつうにかけてる。それもコックコートで。大綬や中綬を付けるときって、モーニングかイヴニングの**礼装**ですよね。コックコート=仕事着=礼装? ちょっとした謎です。いろんなディプロマミルの販売しているものだということは知ってますけど、あれを見て「だから?」と思うひとよりも「スゲー」と思うひとのほうが多いんでしょうか? モンドセレクション?

**Comment by kwikj** [comment]
アレ、ずっと謎だったんです… なんか その昔の大乗仏教的な… 偉いんですよね、きっと。

**Comment by lespoucesverts** [comment]
ネタとしていまいち? だったので早々にクローズします。精神不安定ですみません。
